config/routes.rb
Rails.application.routes.draw do
  get 'users/week_ranking'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :users, only: [:show] do
    member do
      get :followings, :followers
    end
  end
  resources :follow_relationships, only: %i[create destroy]
  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :likes, only: [:create]
    resource :like, only: [:destroy]
  end

  root to: 'tops#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shares/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shares/_footer.html.erb
<footer>
  © 2020 Further_Efforts
</footer>

app/views/shares/_likeduser.html.erb
<div class="show_like_btn">
  <% if current_user.already_liked?(post) %>
    <%= link_to post_like_path(post.id), method: :delete, remote: true, :id => "like_delete",:class => "btn-decoration" do%>
      <button class="btn btn-outline-secondary">いいね！済み</button>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post.id), method: :post, remote: true, :id => "like_create", :class => "btn-decoration" do%>
      <button class="btn btn-outline-secondary">いいね！</button>
    <% end %>
  <% end %>
</div>
<h4>いいねしたユーザー: <%= post.likes.count %></h4>
<% post.liked_users.each do |liked_user| %>
  <div class="show_like_users">
    <%= link_to user_path(liked_user.id), :class => "link_reset" do %>
      <%= render partial: "shares/user_avatar", locals: {user: liked_user} %>
      <%= liked_user.name %>
    <% end %>
  </div>
<% end %>

app/views/shares/_likeform.html.erb
<% if current_user.already_liked?(post) %>
  <%= link_to post_like_path(post.id), method: :delete, remote: true, :id => "like_delete",:class => "btn-decoration" do%>
    <i class="fas fa-heart"></i>
  <% end %>
<% else %>
  <%= link_to post_likes_path(post.id), method: :post, remote: true, :id => "like_create", :class => "btn-decoration" do%>
    <i class="far fa-heart"></i>
  <% end %>
<% end %>
<span>: <%= post.likes.count %></span>

app/views/shares/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Further Efforts</a>
  <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse collapse" id="navbarColor01" style="">
    <ul class="navbar-nav mr-auto navbar-right">
      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="/posts">投稿一覧</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/posts/new">投稿する</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/users/week_ranking">週間ランキング</a>
        </li>

        <li class="nav-item">
        <%= link_to "#{current_user.name}", "/users/#{current_user.id}", :class => 'nav-link' %>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/users/sign_out" onclick="return confirm('本当にログアウトしますか？')">ログアウト</a>
        </li>

      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/posts">投稿一覧</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/posts/new">投稿する</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/users/sign_in">ログイン</a>
        </li>
        
        <li class="nav-item">
          <a class="nav-link" href="/users/sign_up">新規登録</a>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shares/_post_action.html.erb
<% if post.user_id == current_user.id %>
  <%= link_to edit_post_path(post.id), :class => "btn-decoration" do %>
    <i class="far fa-edit action-btn"></i>
  <% end %>
  <%= link_to post_path(post.id), method: :delete, :id => 'delete', :class => "btn-decoration", :onclick => "return confirm('本当に削除しますか？')" do %>
    <i class="far fa-trash-alt action-btn"></i>
  <% end %>
<% end %>

app/views/shares/_post_edit_and_destroy.html.erb
<% if post.user_id == current_user.id %>
  <%= link_to edit_post_path(post.id), :class => "link_style" do %>
    <i class="far fa-edit action-btn"></i>
  <% end %>
  
  <%= link_to post_path(post.id), method: :delete, :id => 'delete', :class => "link_style", :onclick => "return confirm('本当に削除しますか？')" do %>
    <i class="far fa-trash-alt action-btn"></i>
  <% end %>
<% end %>

app/views/shares/_posts_box_container.erb
<div class="posts_boxs_container">
  <% posts.each do |post| %>
    <div class="posts_boxs_fream">
      <%= link_to post_path(post) do %>
        <div class="post_box btn paper-raise">
          <div class="post_do_user_profile">
            <ul>
              <li>
                <p><%= user_avatar_70(post.user) %></p>
              </li>

              <li>
                <%= post.user.name %>
              </li>
            </ul>
          </div>

          <ul class="details_during_learning">
            <li>
              <label class="label_adjustment">学習言語</label><br>
              <%= post.learning_language %>
            </li>

            <li>
              <label>メモ</label><br>
              <%= post.memo %>
            </li>

            <li>
              <label>学習時間</label><br>
              <%= post.learned_time / 60 %>時間<%= post.learned_time % 60 %>分
            </li>

            <li>
              <label>累計学習時間(<%= post.learning_language %>)</label><br>
              <%= post.learned_time_total / 60 %>時間<%= post.learned_time_total % 60 %>分
            </li>
          </ul>

          <div class="edit_and_destroy">
            <%= render partial: "shares/post_edit_and_destroy", locals: {post: post} %>
          </div>

          <div class="like_btn" id="like_bottons_<%= post.id %>">
            <%= render partial: "shares/likeform", locals: {post: post} %>  
          </div>

          <div class="created_at">
            <p>投稿日時：<%= post.created_at.strftime("%Y-%m-%d %H:%M") %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>