config/routes.rb
Rails.application.routes.draw do
  get 'users/week_ranking'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :users, only: [:show] do
    member do
      get :followings, :followers
    end
  end
  resources :follow_relationships, only: %i[create destroy]
  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :likes, only: [:create]
    resource :like, only: [:destroy]
  end

  root to: 'tops#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index; end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/tops/index.html.erb
<div class="top_container">
  <div class="slides">
    <div class="slide">
      <img class="slide_img" src="assets/toppage1.jpg" alt="画像1" width="90%" height="400">
    </div>

    <div class="slide">
      <img class="slide_img" src="assets/toppage2.jpg" alt="テスト画像2" width="90%" height="400">
    </div>

    <div class="slide">
      <img class="slide_img" src="assets/toppage3.jpg" alt="テスト画像3" width="90%" height="400">
    </div>
  </div>
  
  <div class="top_title">
    <p>Futher Efforts</p>
    <span>みんなで支え合い、社会の未来を切り開く</span>
  </div>

  <div class="jumbotron">
    <h1 class="display-3">Futher Effortsとは？</h1>

    <p class="lead">成長意欲の高い人がお互いの成長を投稿し、<br>
      応援しあうことで学習効率をあげるサイトです。</p>

    <p class="lead">
    <% unless user_signed_in? %>
      <%= link_to "さぁ、はじめよう！", new_user_session_path, :id => "further_efforts_start", :class => "btn btn-primary btn-lg" %><br>
      <%= link_to '簡単ログイン', users_guest_sign_in_path, method: :post, :id => "guest_sign_in", :class => "btn btn-primary btn-lg" %>
    <% end %>
    </p>
  </div>
</div>

<%= render "shares/footer" %>