config/routes.rb
Rails.application.routes.draw do
  get 'users/week_ranking'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resources :users, only: [:show] do
    member do
      get :followings, :followers
    end
  end
  resources :follow_relationships, only: %i[create destroy]
  resources :posts do
    resources :comments, only: %i[create destroy]
    resources :likes, only: [:create]
    resource :like, only: [:destroy]
  end

  root to: 'tops#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments

  validates :learning_language, presence: true
  validates :memo, presence: true, length: { maximum: 30 }
  validates :learned_time, presence: true, numericality: { only_integer: true, other_than: 0 }

  def user
    User.find_by(id: user_id)
  end

  def learned_time_total
    total = Post.where(
      learning_language: learning_language,
      user_id: user_id
    )
    total.sum(:learned_time)
  end

  enum learning_language: {
    JavaScript: 'JavaScript',
    Ruby: 'Ruby',
    Python: 'Python',
    Go: 'Go',
    Swift: 'Swift',
    'C++': 'C++',
    'C#': 'C#',
    PHP: 'PHP',
    Scala: 'Scala',
    Kotlin: 'Kotlin',
    Java: 'Java'
  }, _prefix: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[index show new edit destroy update create]
  before_action :current_user_authenticate, only: %i[edit destroy update]
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).page(params[:page]).per(6).order('id DESC')
  end

  def show
    @comments = @post.comments.includes(:user)
    @comment = Comment.new
    @like = Like.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.learned_time = calculate_time
    @post.user_id = current_user.id
    if @post.save
      redirect_to posts_path, notice: '投稿しました'
    else
      flash.now[:alert] = '投稿に失敗しました'
      render :new
    end
  end

  def edit; end

  def update
    @post.update(post_params)
    @post.learned_time = calculate_time
    if @post.save
      redirect_to post_path(@post), notice: '編集しました'
    else
      flash.now[:alert] = '編集に失敗しました'
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path, notice: '削除しました'
    else
      flash.now[:alert] = '削除に失敗しました'
      render :show
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:learning_language, :memo)
  end

  def calculate_time
    params[:time]['post_learned_time(4i)'].to_i * 60 + params[:time]['post_learned_time(5i)'].to_i
  end

  def current_user_authenticate
    @post = Post.find(params[:id])
    redirect_to posts_path, notice: '権限がありません' if @post.user_id != current_user.id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div class="comment_post">
  <%= form_with model: [post, comment], local: true do |c| %>
    <%= c.text_field :review, {class: "form-control", placeholder: "コメントを入力してください"} %><br >
    <%= c.hidden_field :post_id, value: @post.id %>
    <%= c.submit 'コメントする', :class => "btn btn-secondary" %>
  <% end %>
</div>
<div class="commented">
  <% comments.each do |comment| %>
    <table class="table table-hover">
      <tr class="table-light">
        <th>
          <a href="/users/<%= comment.user.id %>" class="link_reset">
            <%= render partial: "shares/user_avatar", locals: {user: comment.user} %><%= comment.user.name %> ＞＞ <%= comment.review %>
          </a>
        </th>
        <th>
          <% if comment.user_id == current_user.id %>
            <%= link_to post_comment_path(comment.post.id, comment.id), method: :delete, :id => 'comment_delete', :class => "btn-decoration", :onclick => "return confirm('本当に削除しますか？')" do %>
              <i class="far fa-trash-alt action-btn"></i>
            <% end %>
          <% end %>
        </th>
      </tr>
    </table>
  <% end %>
</div>

app/views/posts/_comments_container.html.erb
<div class="comment_form">
  <%= form_with model: [post, comment], local: true do |f| %>
    <%= f.text_field :body, {class: "form-control", placeholder: "コメントを入力してください"} %><br>

    <%= f.hidden_field :post_id, value: @post.id %>

    <%= f.submit 'コメントする', :class => "btn btn-secondary" %>
  <% end %>
</div>

<div class="commented_users">
  <% comments.each do |commented_user| %>
    <table class="table table-hover">
      <tr class="table-light">
        <th>
          <%= link_to user_path(commented_user.user), :class => "link_style" do %>
            <%= user_avatar_70(commented_user.user) %><%= commented_user.user.name %> ＞＞ <%= commented_user.body %>
          <% end %>
        </th>

        <th>
          <% if commented_user.user_id == current_user.id %>
            <%= link_to post_comment_path(commented_user.post.id, commented_user.id), method: :delete, :id => 'comment_delete', :class => "link_style delete", :onclick => "return confirm('本当に削除しますか？')" do %>
              <i class="far fa-trash-alt action-btn"></i>
            <% end %>
          <% end %>
        </th>
      </tr>
    </table>
  <% end %>
</div>

app/views/posts/_form.html.erb
<div class ="post_f">
  <%= form_with model: post, local: true do |f| %>
    <div class ="post_field">
      <%= f.label :kind, "学習言語" %><br>
      <%= f.select :kind, options_for_select(Post.kinds.keys), {}, {class: "custom-select"} %><br>
    </div>
    <div class ="post_field">
      <%= f.label :body, "コメント" %><br>
      <%= f.text_field :body, :id => "body", :class => "form-control", :placeholder => "コメントを入力してください(必須)" %><br>
    </div>
    <div class ="post_field">
      <%= label :span, "学習した時間" %> <br>
      <%= time_select "time", :post_span, {ignore_date:true, prompt: "--", minute_step: 5}, {id: "span", class: "custom-select time"} %>
    </div>
    <div class ="f_sbumit">
      <input type="submit" name="commit" class="btn btn-primary" data-disable-with="投稿する" value="投稿する">
    </div>
  <% end %>
</div>

app/views/posts/_input_form.html.erb
<div class ="post_form_container">
  <%= form_with model: post, local: true do |f| %>
    <div class ="field">
      <%= f.label :learning_language, "学習言語" %><br>
      <%= f.select :learning_language, options_for_select(Post.learning_languages.keys), {}, {class: "custom-select"} %><br>
    </div>

    <div class ="field">
      <%= f.label :memo, "コメント" %><br>
      <%= f.text_field :memo, :id => "memo", :class => "form-control", :placeholder => "コメントを入力してください(必須)" %><br>
    </div>

    <div class ="field">
      <%= label :learned_time, "学習した時間" %> <br>
      <%= time_select "time", :post_learned_time, {ignore_date:true, prompt: "--", minute_step: 5}, {id: "learned_time", class: "custom-select time"} %>
    </div>

    <div class ="sbumit">
      <%= f.submit  "投稿する", :id => "commit", :class => "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/posts/_likes_container.html.erb
<div class="like_btns">
  <% if current_user.already_liked?(post) %>
    <%= link_to post_like_path(post.id), method: :delete, remote: true, :id => "like_delete" do%>
      <button class="btn btn-outline-secondary">いいね！済み</button>
    <% end %>
  <% else %>
    <%= link_to post_likes_path(post.id), method: :post, remote: true, :id => "like_create" do%>
      <button class="btn btn-outline-secondary">いいね！</button>
    <% end %>
  <% end %>
</div>

<h4>いいねしたユーザー: <%= post.likes.count %></h4>

<% post.liked_users.each do |liked_user| %>
  <div class="liked_user">
    <%= link_to user_path(liked_user.id), :class => "link_style" do %>
      <%= user_avatar_70(liked_user) %>
      <%= liked_user.name %>
    <% end %>
  </div>
<% end %>

app/views/posts/_post_search.html.erb
<%= search_form_for q do |f|%>
  <ul>
    <li>
      <%= f.select :kind_in, options_for_select(Post.kinds.keys), {include_blank: '言語選択'}, {onclick: "return false;", onchange: "", class: "custom-select"} %>
    </li>
    <li>
      <%= f.search_field :user_name_cont, :placeholder => "名前で検索する", :class => "form-control" %>
    </li>
    <li>
      <%= f.submit "検索", :class => "btn btn-secondary" %>
    </li>
  </ul>
<% end %>

app/views/posts/_post_show_box.html.erb
<div class="card border-secondary mb-3">
  <div class="card-header">
    <h1><%= post.kind %></h1>
  </div>
  <div class="card-body">
    <div class="card-body-colum">
      <p class="card-texts">メモ</p>
      <h2 class="card-title"><%= post.body %></h2>
    </div>
    <div class="card-body-colum">
      <p class="card-texts">学習時間</p>
      <h2 class="card-title"><%= post.span / 60 %>時間<%= post.span % 60 %>分</h2>
    </div>
    <div class="card-body-colum">
      <p class="card-texts">累計学習時間</p>
      <h2 class="card-title"><%= post.span_total / 60 %>時間<%= post.span_total % 60 %>分</h2>
    </div>
    <div class="card-body-colum">
      <p class="card-texts">投稿日時</p>
      <h2 class="card-title"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></h2>
    </div>
  </div>
</div>

app/views/posts/_post_show_box_container.html.erb
<div class="card border-secondary mb-3">
  <div class="card-header">
    <h1><%= post.learning_language %></h1>
  </div>

  <div class="card-body">
    <div class="card-body-colum">
      <p class="card-texts">メモ</p>
      <h2 class="card-title"><%= post.memo %></h2>
    </div>

    <div class="card-body-colum">
      <p class="card-texts">学習時間</p>
      <h2 class="card-title"><%= post.learned_time / 60 %>時間<%= post.learned_time % 60 %>分</h2>
    </div>

    <div class="card-body-colum">
      <p class="card-texts">累計学習時間</p>
      <h2 class="card-title"><%= post.learned_time_total / 60 %>時間<%= post.learned_time_total % 60 %>分</h2>
    </div>
    
    <div class="card-body-colum">
      <p class="card-texts">投稿日時</p>
      <h2 class="card-title"><%= post.created_at.strftime("%Y-%m-%d %H:%M") %></h2>
    </div>
  </div>
</div>

app/views/posts/_posts_index_box.erb
<div class="post_container">
  <% posts.each do |post| %>
    <div class="post_box_fream">
      <a href="/posts/<%= post.id %>" class="font_brack">
        <div class="post_box btn paper-raise">
          <div class="post_user_profile">
            <ul>
              <li>
                <p><%= render partial: "shares/user_avatar", locals: {user: post.user} %></p>
              </li>
              <li>
                <%= post.user.name %>
              </li>
            </ul>
          </div>
          <ul class="learning_profile">
            <li>
              <label class="adjustment">学習言語</label><br>
              <%= post.kind %>
            </li>
            <li>
              <label>メモ</label><br>
              <%= post.body %>
            </li>
            <li>
              <label>学習時間</label><br>
              <%= post.span / 60 %>時間<%= post.span % 60 %>分
            </li>
            <li>
              <label>累計学習時間(<%= post.kind %>)</label><br>
              <%= post.span_total / 60 %>時間<%= post.span_total % 60 %>分
            </li>
          </ul>
          <div class="post_edit_destroy_btn">
            <%= render partial: "shares/post_edit_and_destroy", locals: {post: post} %>
          </div>
          <div class="post_like_btn" id="like_bottons_<%= post.id %>">
            <%= render partial: "shares/likeform", locals: {post: post} %>  
          </div>
          <div class="post_created_at">
            <p>投稿日時：<%= post.created_at.strftime("%Y-%m-%d %H:%M") %></p>
          </div>
        </div>
      </a>
    </div>
  <% end %>
</div>

app/views/posts/_search_container.html.erb
<%= search_form_for q do |f|%>
  <ul>
    <li>
      <%= f.select :learning_language_in, options_for_select(Post.learning_languages.keys), {include_blank: '言語選択'}, {onclick: "return false;", onchange: "", class: "custom-select"} %>
    </li>

    <li>
      <%= f.search_field :user_name_cont, :placeholder => "名前で検索する", :class => "form-control" %>
    </li>

    <li>
      <%= f.submit "検索", :class => "btn btn-secondary" %>
    </li>
  </ul>
<% end %>

app/views/posts/edit.html.erb
<%= render partial: "input_form", locals: {post: @post} %>

<%= render "shares/footer" %>

app/views/posts/index.html.erb
<div class="posts_header">
  <h1>みんなの努力の掲示板</h1>
  <h3>さぁ、あなたも投稿して応援してもらおう！</h3>
  <button type="button" onclick="location.href='/posts/new'" class="btn btn-primary btn-lg btn-block">投稿してみる</button>

  <%= render partial: 'search_container', locals: {q: @q} %>
</div>

<%= render partial: "shares/posts_box_container", locals: {posts: @posts} %>

<%= paginate(@posts) %>

<%= render "shares/footer" %>

app/views/posts/new.html.erb
<div class="posts_header">
  <h1>新規投稿</h1>
  <h3>学習した内容を掲示板に記そう！！</h3>
</div>

<%= render partial: "input_form", locals: {post: @post} %>

<%= render "shares/footer" %>

app/views/posts/show.html.erb
<div class="posts_show_container">
  <div class="posts_show_user">
    <%= link_to user_path(@post.user), :class => "link_style" do %>
      <%= user_avatar_150(@post.user) %>

      <h1><%= @post.user.name %></h1>
    <% end %>
  </div>

  <%= render partial: "post_show_box_container", locals: {post: @post} %>

  <div class="edit_and_destroy">
    <%= render partial: "shares/post_edit_and_destroy", locals: {post: @post} %>
  </div>

  <p class="border"></p>

  <div class ="likes_container" id="likes_container">
    <%= render partial: "likes_container", locals: {post: @post} %>
  </div>

  <p class="border"></p>

  <div class="comments_container">
    <h4>コメント一覧</h4>

    <%= render partial: "comments_container", locals: {comment: @comment, post: @post, comments: @comments} %>
  </div>
</div>

<%= render "shares/footer" %>